// AUTO-GENERATED by scripts/build-knowledge.mjs — do not edit by hand. Run: npm run kb
export const KNOWLEDGE = [
 {
  "id": "kb-1",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Custom Website Design",
  "text": "title: Custom Website Design\nshortDesc: Visually stunning, responsive designs tailored to your brand and business needs.\nfullDesc: We craft bespoke websites that reflect your brand identity and engage your audience. Every design is built mobile-first, ensuring a flawless experience across all devices. From wireframes to final launch, we collaborate closely with you at every stage — creating websites that don't just look incredible but actually convert visitors into paying customers.\nfeatures: \n- Custom UI/UX Design\n- Mobile-First Approach\n- Brand-Aligned Aesthetics\n- CMS Integration\n- Speed Optimised\n- SEO-Ready Structure\n- Accessible & WCAG Compliant\nprocess: \nstep: 1\ntitle: Discovery Call\ndesc: We learn about your business, goals, target audience, and design preferences.\nstep: 2\ntitle: Wireframes & Concepts\ndesc: We sketch the layout and structure before any pixel is designed.\nstep: 3\ntitle: Design Mockups\ndesc: Full high-fidelity designs presented for your review and feedback.\nstep: 4\ntitle: Development & Testing\ndesc: We build your site, test across all devices, and squash every bug.\nstep: 5\ntitle: Launch & Handover\ndesc: We go live and walk you through managing your new website.\nbenefits: \ntitle: Fully Responsive\ndesc: Pixel-perfect on every device — desktop, tablet, and mobile.\ntitle: Lightning Fast\ndesc: Optimised for Core Web Vitals and Google PageSpeed.\ntitle: Built for SEO\ndesc: Clean structure, semantic markup, and meta-optimised from day one."
 },
 {
  "id": "kb-2",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Web & Mobile Development",
  "text": "title: Web & Mobile Development\nshortDesc: Powerful websites and applications built for speed, security, and performance.\nfullDesc: Our development team builds robust web and mobile applications using the latest technologies. Whether you need a complex web app or a cross-platform mobile solution, we deliver scalable, maintainable code that stands the test of time. We work with React, Next.js, Node.js, and Flutter to give you the best fit for your project.\nfeatures: \n- React & Next.js Development\n- iOS & Android Apps\n- API Integration\n- Secure Architecture\n- Ongoing Maintenance\n- Cloud Hosting Setup\n- Performance Monitoring\nprocess: \nstep: 1\ntitle: Requirements Gathering\ndesc: We map out every feature, user journey, and technical requirement.\nstep: 2\ntitle: Architecture Planning\ndesc: We design the system architecture for scalability and security.\nstep: 3\ntitle: Agile Development\ndesc: Build in sprints with regular demos so you always see progress.\nstep: 4\ntitle: QA & Testing\ndesc: Rigorous testing across browsers, devices, and edge cases.\nstep: 5\ntitle: Deployment & Support\ndesc: Smooth deployment and ongoing technical support post-launch.\nbenefits: \ntitle: Secure by Default\ndesc: Industry best practices for authentication, data protection, and GDPR.\ntitle: Built to Scale\ndesc: Architecture that grows with your business without expensive rewrites.\ntitle: Ongoing Support\ndesc: We don't disappear after launch — we're here when you need us."
 },
 {
  "id": "kb-3",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "E-commerce Website Development",
  "text": "title: E-commerce Website Development\nshortDesc: Online stores built to convert, scale, and grow with your business.\nfullDesc: We build high-converting e-commerce platforms that make buying easy and selling effortless. From product pages to checkout flows, every element is optimised for maximum conversion. We work with WooCommerce, Shopify, and custom solutions — always with a laser focus on turning visitors into customers and customers into repeat buyers.\nfeatures: \n- WooCommerce & Shopify\n- Custom Checkout Flows\n- Product Management\n- Payment Gateway Integration\n- Inventory Management\n- Abandoned Cart Recovery\n- Multi-Currency Support\nprocess: \nstep: 1\ntitle: Platform Selection\ndesc: We help you choose the right platform for your products and goals.\nstep: 2\ntitle: Store Design\ndesc: Conversion-focused design that builds trust and drives sales.\nstep: 3\ntitle: Product Setup\ndesc: Full catalogue setup with optimised images, descriptions, and categories.\nstep: 4\ntitle: Payments & Shipping\ndesc: Integrate payment gateways and configure shipping rules and zones.\nstep: 5\ntitle: Launch & Marketing\ndesc: Go live with an SEO foundation and launch marketing strategy.\nbenefits: \ntitle: Conversion Optimised\ndesc: Every page element is designed to reduce friction and increase sales.\ntitle: Secure Checkout\ndesc: PCI-compliant, SSL-secured, and trusted payment integrations.\ntitle: Analytics Ready\ndesc: Full GA4 and ecommerce tracking so you know exactly what's selling."
 },
 {
  "id": "kb-4",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Search Engine Optimization (SEO)",
  "text": "title: Search Engine Optimization (SEO)\nshortDesc: Get found on Google and drive organic traffic with expert SEO strategies.\nfullDesc: Our SEO specialists use data-driven strategies to help your business rank higher in search results. We focus on sustainable, white-hat techniques that deliver long-term growth — from technical SEO audits to content strategy and link building. Whether you're a local business in Leeds or targeting a national audience, we build an SEO strategy tailored specifically to your goals.\nfeatures: \n- Keyword Research\n- On-Page Optimisation\n- Technical SEO Audits\n- Local SEO (Leeds)\n- Monthly Reporting\n- Link Building\n- Content Strategy\nprocess: \nstep: 1\ntitle: SEO Audit\ndesc: Comprehensive audit of your current site — technical, on-page, and off-page.\nstep: 2\ntitle: Keyword Strategy\ndesc: Research and map high-intent keywords to your key pages.\nstep: 3\ntitle: On-Page Optimisation\ndesc: Optimise titles, meta, headings, content, and internal linking.\nstep: 4\ntitle: Technical Fixes\ndesc: Fix site speed, crawlability, structured data, and mobile issues.\nstep: 5\ntitle: Monitor & Report\ndesc: Monthly reports showing rankings, traffic growth, and ROI.\nbenefits: \ntitle: Top Google Rankings\ndesc: Proven track record of getting clients to page 1 for competitive terms.\ntitle: Long-Term Results\ndesc: White-hat strategies that compound over time — no shortcuts.\ntitle: Local SEO Experts\ndesc: Specialists in Leeds and UK local SEO to dominate your area."
 },
 {
  "id": "kb-5",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Website Management",
  "text": "title: Website Management\nshortDesc: Ongoing care, updates, and protection to keep your site running smoothly.\nfullDesc: Keep your website secure, fast, and up-to-date with our comprehensive website management packages. We handle plugin updates, security monitoring, backups, content updates, and performance optimisation so you can focus on running your business. Think of us as your dedicated web team — available whenever you need us.\nfeatures: \n- Security Monitoring\n- Regular Backups\n- Plugin & CMS Updates\n- Performance Optimisation\n- Content Updates\n- 24/7 Uptime Monitoring\n- Emergency Support\nprocess: \nstep: 1\ntitle: Site Audit\ndesc: We assess your current setup, identify risks, and create a maintenance plan.\nstep: 2\ntitle: Security Hardening\ndesc: Install protections, firewalls, and monitoring tools.\nstep: 3\ntitle: Backup System\ndesc: Set up automated daily backups stored securely off-site.\nstep: 4\ntitle: Regular Maintenance\ndesc: Monthly updates, speed checks, and security scans.\nstep: 5\ntitle: Report & Review\ndesc: Monthly reports and proactive recommendations.\nbenefits: \ntitle: Proactive Monitoring\ndesc: We catch issues before they become problems — often before you even notice.\ntitle: Saves You Time\ndesc: Stop worrying about updates and security — we handle everything.\ntitle: Always Up-to-Date\ndesc: Plugins, themes, and CMS always on the latest secure versions."
 },
 {
  "id": "kb-6",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Graphic Design Services",
  "text": "title: Graphic Design Services\nshortDesc: Logos, branding, flyers, and everything in between to bring your brand to life.\nfullDesc: From logo design to full brand identity packages, our graphic designers create visuals that make your business unforgettable. We produce everything from business cards and flyers to social media graphics and presentation decks. Great design isn't just pretty — it communicates your values, builds trust, and sets you apart from the competition.\nfeatures: \n- Logo & Brand Identity\n- Social Media Graphics\n- Print Design\n- Marketing Materials\n- Brand Guidelines\n- Business Cards & Stationery\n- Packaging Design\nprocess: \nstep: 1\ntitle: Brand Discovery\ndesc: We dig into your brand values, audience, and visual preferences.\nstep: 2\ntitle: Concept Development\ndesc: Multiple initial concepts presented for your feedback.\nstep: 3\ntitle: Design Refinement\ndesc: Iterate based on your feedback until the design is perfect.\nstep: 4\ntitle: Final Delivery\ndesc: All files delivered in every format you'll ever need.\nstep: 5\ntitle: Brand Guidelines\ndesc: A full guide on how to use your brand consistently.\nbenefits: \ntitle: Stand Out\ndesc: Distinctive visuals that make you instantly recognisable in a crowded market.\ntitle: Build Trust\ndesc: Professional design signals quality and credibility to potential customers.\ntitle: All Files Included\ndesc: Full source files (AI, EPS, SVG, PDF, PNG) — yours to keep forever."
 },
 {
  "id": "kb-7",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Video Animation",
  "text": "title: Video Animation\nshortDesc: Captivating animated videos that tell your brand story, explain products, and engage audiences.\nfullDesc: From explainer animations to full brand videos, we bring your message to life through motion. Our animation team crafts visually compelling content that captures attention on social media, websites, and presentations. We handle everything from scripting and storyboarding to final delivery in any format you need.\nfeatures: \n- Explainer Videos\n- Social Media Animations\n- Motion Graphics & Intros\n- Brand Story Videos\n- Script & Storyboard Included\n- Voice-Over Services\n- Multi-Format Delivery\nprocess: \nstep: 1\ntitle: Brief & Script\ndesc: We write a compelling script that communicates your message clearly.\nstep: 2\ntitle: Storyboard\ndesc: Visual storyboard shows exactly how the animation will flow.\nstep: 3\ntitle: Design & Animation\ndesc: Our animators bring the storyboard to life with motion and sound.\nstep: 4\ntitle: Review & Revisions\ndesc: Watch the draft, give feedback, we refine until it's spot on.\nstep: 5\ntitle: Final Delivery\ndesc: Delivered in MP4, MOV, GIF, and any other format you need.\nbenefits: \ntitle: Boost Engagement\ndesc: Video content gets 5x more engagement than static posts on social media.\ntitle: Explain Anything\ndesc: Complex products or services explained simply and memorably in 60–90 seconds.\ntitle: Works Everywhere\ndesc: Optimised for website, YouTube, Instagram, LinkedIn, and more."
 },
 {
  "id": "kb-8",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Digital Marketing",
  "text": "title: Digital Marketing\nshortDesc: Data-driven digital marketing strategies that grow your audience, increase leads, and boost revenue.\nfullDesc: Reach the right people at the right time with our comprehensive digital marketing services. We develop tailored strategies across social media, email, paid ads, and content marketing to drive measurable results. Every campaign is tracked, analysed, and continuously optimised to maximise your return on investment.\nfeatures: \n- Social Media Marketing\n- Google & Meta Ads (PPC)\n- Email Marketing Campaigns\n- Content Marketing Strategy\n- Monthly Analytics Reports\n- Audience Research\n- Competitor Analysis\nprocess: \nstep: 1\ntitle: Strategy & Goals\ndesc: Define your KPIs, audience, and channels for maximum impact.\nstep: 2\ntitle: Campaign Planning\ndesc: Build a multi-channel plan with content calendar and ad creatives.\nstep: 3\ntitle: Launch Campaigns\ndesc: Go live across chosen platforms with A/B tested ad variations.\nstep: 4\ntitle: Optimise & Scale\ndesc: Analyse performance data weekly and double down on what works.\nstep: 5\ntitle: Monthly Reporting\ndesc: Clear ROI reports showing exactly what your budget achieved.\nbenefits: \ntitle: Precision Targeting\ndesc: Reach exactly the right people with laser-targeted audience segments.\ntitle: Full Transparency\ndesc: Every metric tracked and reported — no vanity numbers, real ROI.\ntitle: Scalable Growth\ndesc: Start small, prove results, then scale your budget with confidence."
 },
 {
  "id": "kb-9",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Pay Per Click Advertising (PPC)",
  "text": "title: Pay Per Click Advertising (PPC)\nshortDesc: Instant visibility on Google and social platforms with highly targeted ad campaigns that deliver measurable ROI.\nfullDesc: Stop waiting for organic traffic — PPC puts your business in front of the right people immediately. Our certified Google Ads and Meta Ads specialists build laser-targeted campaigns that maximise every penny of your ad spend. From keyword research and ad copywriting to landing page optimisation and daily bid management, we handle everything while you watch the leads roll in.\nfeatures: \n- Google Ads (Search & Display)\n- Meta Ads (Facebook & Instagram)\n- Keyword Research & Bid Strategy\n- Ad Copywriting & Creative\n- Landing Page Optimisation\n- Daily Campaign Management\n- Monthly ROI Reports\nprocess: \nstep: 1\ntitle: Audit & Research\ndesc: Analyse your market, competitors, and best-performing keywords.\nstep: 2\ntitle: Campaign Setup\ndesc: Build tightly themed ad groups with compelling ad copy.\nstep: 3\ntitle: Landing Pages\ndesc: Create or optimise landing pages for maximum conversion rate.\nstep: 4\ntitle: Launch & Monitor\ndesc: Launch campaigns and monitor performance from day one.\nstep: 5\ntitle: Optimise & Report\ndesc: Continuous bid optimisation, A/B testing, and monthly ROI reports.\nbenefits: \ntitle: Instant Results\ndesc: Appear on page 1 of Google within 24 hours of campaign launch.\ntitle: Every Penny Tracked\ndesc: Know exactly what each click, lead, and sale costs you.\ntitle: Certified Specialists\ndesc: Google and Meta certified ads managers running your campaigns."
 },
 {
  "id": "kb-10",
  "source": "mocks/servicesData",
  "category": "services",
  "url": "/services",
  "title": "Social Media Marketing",
  "text": "title: Social Media Marketing\nshortDesc: Build a loyal community and grow your brand across Facebook, Instagram, TikTok, and LinkedIn.\nfullDesc: Social media is where your customers spend their time — and we make sure your brand is there, looking brilliant. Our social media team creates engaging, on-brand content tailored to each platform, manages your community, and runs data-driven campaigns to grow your following and generate real business leads.\nfeatures: \n- Facebook & Instagram Management\n- TikTok & LinkedIn Strategy\n- Content Creation & Scheduling\n- Community Management & Replies\n- Paid Social Ad Campaigns\n- Hashtag & Audience Research\n- Monthly Growth Analytics\nprocess: \nstep: 1\ntitle: Social Audit\ndesc: Review your existing profiles, audience, and competitors.\nstep: 2\ntitle: Content Strategy\ndesc: Develop a content calendar aligned with your brand and goals.\nstep: 3\ntitle: Content Creation\ndesc: Produce scroll-stopping graphics, videos, and captions for every post.\nstep: 4\ntitle: Scheduling & Publishing\ndesc: Post at optimal times for maximum reach and engagement.\nstep: 5\ntitle: Engage & Grow\ndesc: Respond to comments, grow your following, and report monthly.\nbenefits: \ntitle: Build Community\ndesc: Turn followers into fans who advocate for your brand organically.\ntitle: On-Brand Content\ndesc: Every post looks professionally designed and consistent with your identity.\ntitle: Measurable Growth\ndesc: Track follower growth, reach, engagement rate, and leads generated."
 },
 {
  "id": "kb-11",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "web-design — Starter",
  "text": "service: web-design\nname: Starter\nprice: £299\nperiod: one-time\ntag: Great Value\ndescription: Perfect for small businesses & startups who need a clean, professional online presence fast.\nitems: \n- Up to 3 custom-designed pages\n- Mobile & tablet responsive\n- Basic SEO setup (titles & meta)\n- Contact form integration\n- 1 round of revisions\n- Delivered in 7–10 days"
 },
 {
  "id": "kb-12",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "web-design — Growth",
  "text": "service: web-design\nname: Growth\nprice: £699\nperiod: one-time\ntag: Most Popular\ndescription: Ideal for growing businesses that want a polished site with more pages and functionality.\nitems: \n- Up to 8 custom-designed pages\n- CMS integration (WordPress / Webflow)\n- Full SEO-ready structure\n- Speed & performance optimised\n- Google Analytics setup\n- 3 rounds of revisions\n- Delivered in 2–3 weeks"
 },
 {
  "id": "kb-13",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "web-design — Premium",
  "text": "service: web-design\nname: Premium\nprice: Custom\nperiod: quote\ntag: Enterprise\ndescription: For brands that demand a fully bespoke, conversion-focused website with no compromises.\nitems: \n- Unlimited pages & sections\n- Advanced animations & interactions\n- E-commerce or booking integration\n- Brand identity alignment\n- Ongoing support package\n- Priority 5-day turnaround\n- Dedicated project manager"
 },
 {
  "id": "kb-14",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "web-mobile — Starter",
  "text": "service: web-mobile\nname: Starter\nprice: £449\nperiod: one-time\ntag: Great Value\ndescription: A solid web application or landing page — built clean, fast, and ready to deploy.\nitems: \n- React / HTML web app\n- Fully mobile responsive\n- Basic API or form integration\n- Hosting & deployment guidance\n- 1 round of revisions\n- Delivered in 1–2 weeks"
 },
 {
  "id": "kb-15",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "web-mobile — Growth",
  "text": "service: web-mobile\nname: Growth\nprice: £999\nperiod: one-time\ntag: Most Popular\ndescription: A full-featured web application with auth, API integrations, and production-ready code.\nitems: \n- React / Next.js web application\n- User authentication\n- Third-party API integrations\n- Database setup & connection\n- Cloud deployment included\n- 3 rounds of revisions\n- 30-day post-launch support"
 },
 {
  "id": "kb-16",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "web-mobile — Premium",
  "text": "service: web-mobile\nname: Premium\nprice: Custom\nperiod: quote\ntag: Enterprise\ndescription: Full-stack web + mobile apps built for scale, security, and long-term performance.\nitems: \n- iOS & Android mobile app (Flutter)\n- Complex business logic & workflows\n- Real-time features & notifications\n- Scalable cloud architecture\n- Performance monitoring setup\n- Ongoing maintenance retainer\n- Dedicated dev team"
 },
 {
  "id": "kb-17",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "ecommerce — Starter",
  "text": "service: ecommerce\nname: Starter\nprice: £399\nperiod: one-time\ntag: Great Value\ndescription: Get your online shop live quickly with a clean, conversion-ready store built to sell.\nitems: \n- Up to 20 products setup\n- WooCommerce or Shopify\n- Payment gateway integration\n- Mobile-friendly storefront\n- Basic SEO configuration\n- Delivered in 1–2 weeks"
 },
 {
  "id": "kb-18",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "ecommerce — Growth",
  "text": "service: ecommerce\nname: Growth\nprice: £899\nperiod: one-time\ntag: Most Popular\ndescription: A fully featured store with custom design, advanced features, and a solid foundation to scale.\nitems: \n- Up to 75 products with full setup\n- Custom store theme design\n- Abandoned cart recovery\n- Email capture & integrations\n- Shipping & tax configuration\n- Google Analytics & tracking\n- 3 rounds of revisions"
 },
 {
  "id": "kb-19",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "ecommerce — Premium",
  "text": "service: ecommerce\nname: Premium\nprice: Custom\nperiod: quote\ntag: Enterprise\ndescription: Bespoke e-commerce for high-volume stores that need serious power and customisation.\nitems: \n- Unlimited products\n- Custom checkout & upsell flows\n- Multi-currency & multi-language\n- Inventory & subscription system\n- Advanced reporting dashboard\n- Ongoing management retainer\n- Dedicated account manager"
 },
 {
  "id": "kb-20",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "seo — Starter",
  "text": "service: seo\nname: Starter\nprice: £149\nperiod: /mo\ntag: Great Value\ndescription: Local SEO essentials to get your business found in your area — straightforward and effective.\nitems: \n- 5 target keywords\n- Google My Business optimisation\n- On-page SEO (up to 3 pages)\n- Basic technical SEO audit\n- Monthly ranking report\n- No contract — cancel anytime"
 },
 {
  "id": "kb-21",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "seo — Growth",
  "text": "service: seo\nname: Growth\nprice: £299\nperiod: /mo\ntag: Most Popular\ndescription: A full SEO campaign covering on-page, technical, and off-page to build sustainable rankings.\nitems: \n- 15 target keywords\n- Full on-page & technical SEO\n- Monthly link building\n- Content optimisation\n- Competitor tracking\n- Bi-weekly progress reports\n- Quarterly strategy review"
 },
 {
  "id": "kb-22",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "seo — Premium",
  "text": "service: seo\nname: Premium\nprice: £599\nperiod: /mo\ntag: Enterprise\ndescription: A fully managed SEO strategy for businesses serious about dominating search results.\nitems: \n- Unlimited keywords\n- Full content creation included\n- Authority link building\n- Schema & structured data\n- Core Web Vitals optimisation\n- Weekly reporting & calls\n- Dedicated SEO manager"
 },
 {
  "id": "kb-23",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "management — Starter",
  "text": "service: management\nname: Starter\nprice: £79\nperiod: /mo\ntag: Great Value\ndescription: Essential care for your website — keeping it secure, backed up, and always online.\nitems: \n- Monthly backups (off-site storage)\n- Security monitoring & scanning\n- Plugin & CMS updates\n- Uptime monitoring (24/7)\n- Monthly status report\n- No contract — cancel anytime"
 },
 {
  "id": "kb-24",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "management — Growth",
  "text": "service: management\nname: Growth\nprice: £149\nperiod: /mo\ntag: Most Popular\ndescription: Regular hands-on care with priority support and content updates included.\nitems: \n- Weekly backups (off-site storage)\n- Priority support (48hr response)\n- Performance optimisation monthly\n- 1 content update per month\n- Security hardening\n- Speed & Core Web Vitals checks\n- Monthly detailed report"
 },
 {
  "id": "kb-25",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "management — Premium",
  "text": "service: management\nname: Premium\nprice: £299\nperiod: /mo\ntag: Enterprise\ndescription: Your fully outsourced web team — unlimited updates, emergency cover, and proactive management.\nitems: \n- Daily automated backups\n- Emergency support (same-day)\n- Unlimited content updates\n- Full performance management\n- Malware removal included\n- Staging environment setup\n- Dedicated account manager"
 },
 {
  "id": "kb-26",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "graphic — Starter",
  "text": "service: graphic\nname: Starter\nprice: £149\nperiod: one-time\ntag: Great Value\ndescription: A professional logo that gives your brand a strong identity — without the big agency price tag.\nitems: \n- Logo design (2 initial concepts)\n- 2 rounds of revisions\n- PNG, JPG & PDF delivery\n- Black & white versions included\n- Delivered in 5–7 days"
 },
 {
  "id": "kb-27",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "graphic — Growth",
  "text": "service: graphic\nname: Growth\nprice: £349\nperiod: one-time\ntag: Most Popular\ndescription: A full brand identity kit — everything you need to look consistent and professional everywhere.\nitems: \n- Logo design (3 concepts)\n- Brand colour palette & typography\n- Business card design\n- Letterhead & email signature\n- Social media profile & cover designs\n- All source files (AI, EPS, SVG, PDF, PNG)\n- 3 rounds of revisions"
 },
 {
  "id": "kb-28",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "graphic — Premium",
  "text": "service: graphic\nname: Premium\nprice: £699+\nperiod: one-time\ntag: Enterprise\ndescription: A complete brand package — from identity to print to packaging, all under one roof.\nitems: \n- Everything in Growth\n- Full brand guidelines document\n- Flyer & marketing material design\n- Packaging design\n- Presentation deck template\n- Social media template set\n- Priority 5-day delivery"
 },
 {
  "id": "kb-29",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "video — Starter",
  "text": "service: video\nname: Starter\nprice: £299\nperiod: one-time\ntag: Great Value\ndescription: A punchy 30-second animated explainer — perfect for social media or your homepage.\nitems: \n- Up to 30-second animation\n- Script writing included\n- Custom motion graphics\n- Royalty-free music\n- 1 round of revisions\n- MP4 delivery\n- Delivered in 10–14 days"
 },
 {
  "id": "kb-30",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "video — Growth",
  "text": "service: video\nname: Growth\nprice: £599\nperiod: one-time\ntag: Most Popular\ndescription: A fully produced 60-second animated brand video with voice-over and premium sound design.\nitems: \n- Up to 60-second animation\n- Script & storyboard included\n- Professional voice-over\n- Custom music & sound effects\n- 2 rounds of revisions\n- MP4, MOV & GIF delivery\n- Delivered in 2–3 weeks"
 },
 {
  "id": "kb-31",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "video — Premium",
  "text": "service: video\nname: Premium\nprice: £1,200+\nperiod: one-time\ntag: Enterprise\ndescription: A long-form brand video or series — character animation, advanced motion, full production.\nitems: \n- 90 seconds or longer\n- Custom character animation\n- Advanced motion graphics\n- Full voiceover production\n- 3+ rounds of revisions\n- All formats & resolutions\n- Subtitles & captions included"
 },
 {
  "id": "kb-32",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "digital-marketing — Starter",
  "text": "service: digital-marketing\nname: Starter\nprice: £199\nperiod: /mo\ntag: Great Value\ndescription: Kick off your digital presence with a focused strategy across email and social media.\nitems: \n- 2 social media channels managed\n- 8 posts per month\n- Monthly email campaign\n- Audience & competitor research\n- Monthly analytics report\n- No contract — cancel anytime"
 },
 {
  "id": "kb-33",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "digital-marketing — Growth",
  "text": "service: digital-marketing\nname: Growth\nprice: £449\nperiod: /mo\ntag: Most Popular\ndescription: A multi-channel digital marketing strategy that drives real leads and grows your brand.\nitems: \n- 3 social media channels managed\n- 16 posts + stories per month\n- Google & Meta Ads management\n- Email marketing (2 campaigns/mo)\n- Content calendar planning\n- Weekly performance review\n- Bi-weekly strategy calls"
 },
 {
  "id": "kb-34",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "digital-marketing — Premium",
  "text": "service: digital-marketing\nname: Premium\nprice: £899\nperiod: /mo\ntag: Enterprise\ndescription: A fully managed digital marketing engine — all channels, all content, maximum ROI.\nitems: \n- All social platforms managed\n- 30+ posts & reels per month\n- Full PPC ad management\n- Weekly email campaigns\n- SEO content writing included\n- Daily performance monitoring\n- Dedicated account manager"
 },
 {
  "id": "kb-35",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "ppc — Starter",
  "text": "service: ppc\nname: Starter\nprice: £199\nperiod: /mo\ntag: Great Value\ndescription: Get on Google Page 1 fast — a focused single-campaign setup to drive immediate leads.\nitems: \n- 1 Google Ads campaign\n- Keyword research & selection\n- Ad copywriting (2 variations)\n- Conversion tracking setup\n- Monthly performance report\n- No contract — cancel anytime"
 },
 {
  "id": "kb-36",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "ppc — Growth",
  "text": "service: ppc\nname: Growth\nprice: £449\nperiod: /mo\ntag: Most Popular\ndescription: Google + Meta Ads running together — targeted, optimised, and delivering consistent leads.\nitems: \n- Google Ads (Search & Display)\n- Meta Ads (Facebook & Instagram)\n- Up to 3 ad campaigns\n- Weekly bid optimisation\n- Landing page recommendations\n- A/B ad testing\n- Bi-weekly ROI reports"
 },
 {
  "id": "kb-37",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "ppc — Premium",
  "text": "service: ppc\nname: Premium\nprice: £899\nperiod: /mo\ntag: Enterprise\ndescription: Full PPC management across every platform — daily oversight, advanced optimisation.\nitems: \n- All platforms (Google, Meta, LinkedIn)\n- Unlimited campaigns\n- Daily bid & budget management\n- Dedicated landing page creation\n- Dynamic retargeting ads\n- Weekly strategy calls\n- Dedicated PPC manager"
 },
 {
  "id": "kb-38",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "social-media-marketing — Starter",
  "text": "service: social-media-marketing\nname: Starter\nprice: £149\nperiod: /mo\ntag: Great Value\ndescription: Establish your brand on social media with consistent, on-brand posting every week.\nitems: \n- 2 platforms (Facebook & Instagram)\n- 8 posts per month\n- Caption writing included\n- Basic hashtag research\n- Monthly growth report\n- No contract — cancel anytime"
 },
 {
  "id": "kb-39",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "social-media-marketing — Growth",
  "text": "service: social-media-marketing\nname: Growth\nprice: £299\nperiod: /mo\ntag: Most Popular\ndescription: Grow your following and drive engagement with a full content strategy across 3 platforms.\nitems: \n- 3 platforms (FB, Instagram, TikTok or LinkedIn)\n- 16 posts + 8 stories per month\n- Custom branded graphics\n- Community management & replies\n- Hashtag & audience research\n- Monthly strategy review\n- Bi-weekly analytics report"
 },
 {
  "id": "kb-40",
  "source": "mocks/servicesPricing",
  "category": "pricing",
  "url": "/pricing",
  "title": "social-media-marketing — Premium",
  "text": "service: social-media-marketing\nname: Premium\nprice: £599\nperiod: /mo\ntag: Enterprise\ndescription: Full-service social media management — content, ads, growth, and community all handled.\nitems: \n- All platforms managed\n- 30+ posts & reels per month\n- Paid social ad campaigns\n- Influencer outreach support\n- User-generated content strategy\n- Daily community management\n- Dedicated social media manager"
 },
 {
  "id": "kb-41",
  "source": "mocks/portfolioItems",
  "category": "portfolio",
  "url": "/portfolio",
  "title": "All Believers Chapel",
  "text": "title: All Believers Chapel\ncategory: Web Design\ndescription: A warm, welcoming church website for All Believers Chapel in Leeds — featuring ministries, events, leadership profiles, donation integration, and a live service schedule."
 },
 {
  "id": "kb-42",
  "source": "mocks/portfolioItems",
  "category": "portfolio",
  "url": "/portfolio",
  "title": "Graphic Design Website",
  "text": "title: Graphic Design Website\ncategory: Web Design\ndescription: A visually stunning portfolio website for a graphic design studio, showcasing their creative work with an immersive gallery experience."
 },
 {
  "id": "kb-43",
  "source": "mocks/portfolioItems",
  "category": "portfolio",
  "url": "/portfolio",
  "title": "Photography Portfolio Site",
  "text": "title: Photography Portfolio Site\ncategory: Web Design\ndescription: An elegant photography portfolio with full-screen imagery, smooth transitions, and a built-in booking system."
 },
 {
  "id": "kb-44",
  "source": "mocks/portfolioItems",
  "category": "portfolio",
  "url": "/portfolio",
  "title": "Cleaning Company Website",
  "text": "title: Cleaning Company Website\ncategory: E-commerce\ndescription: A professional cleaning company website with online booking, service listings, and integrated customer reviews."
 },
 {
  "id": "kb-45",
  "source": "mocks/portfolioItems",
  "category": "portfolio",
  "url": "/portfolio",
  "title": "E.A Sport Photography",
  "text": "title: E.A Sport Photography\ncategory: Photography\ndescription: A dynamic sports photography service website featuring high-impact visuals, athlete galleries, and event booking functionality."
 },
 {
  "id": "kb-46",
  "source": "mocks/portfolioItems",
  "category": "portfolio",
  "url": "/portfolio",
  "title": "E-Commerce Platform",
  "text": "title: E-Commerce Platform\ncategory: E-commerce\ndescription: A fully-featured e-commerce platform built for performance, with custom product pages, secure checkout, and inventory management."
 },
 {
  "id": "kb-47",
  "source": "mocks/portfolioItems",
  "category": "portfolio",
  "url": "/portfolio",
  "title": "SEO Campaign Dashboard",
  "text": "title: SEO Campaign Dashboard\ncategory: SEO\ndescription: A bespoke SEO reporting and analytics dashboard helping a Leeds business track rankings, traffic, and conversions in real-time."
 },
 {
  "id": "kb-48",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "How much does a website cost in Leeds?",
  "text": "category: Web Design\nq: How much does a website cost in Leeds?\na: Website costs in Leeds vary based on complexity. A professional small business website typically starts from £500–£1,500. E-commerce stores, custom web applications, or larger multi-page sites range from £1,500–£5,000+. At Dleading Creative Designs, we offer transparent, fixed-price packages tailored to your budget — no hidden fees. Contact us for a free, no-obligation quote."
 },
 {
  "id": "kb-49",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "How long does it take to build a website in Leeds?",
  "text": "category: Web Design\nq: How long does it take to build a website in Leeds?\na: Most small business websites are completed within 7–21 days from when we receive your content and approval. E-commerce stores typically take 2–5 weeks. Larger custom projects can take 4–8 weeks. Timelines depend on how quickly we receive your content, feedback, and sign-offs. We always agree a target delivery date before we start."
 },
 {
  "id": "kb-50",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you build WordPress websites?",
  "text": "category: Web Design\nq: Do you build WordPress websites?\na: Yes — WordPress is one of our primary platforms. We build fully custom WordPress sites (not off-the-shelf templates) that are fast, secure, mobile-responsive, and easy for you to update yourself. We also provide WordPress training and ongoing management if required."
 },
 {
  "id": "kb-51",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you build Shopify or WooCommerce stores?",
  "text": "category: Web Design\nq: Do you build Shopify or WooCommerce stores?\na: Absolutely. We build both Shopify and WooCommerce e-commerce stores. Shopify is ideal for businesses wanting an easy-to-manage hosted solution, while WooCommerce on WordPress gives more flexibility and ownership. We'll recommend the right platform based on your products, budget, and long-term goals."
 },
 {
  "id": "kb-52",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Will my website be mobile-friendly and responsive?",
  "text": "category: Web Design\nq: Will my website be mobile-friendly and responsive?\na: Yes, every website we build is fully responsive — meaning it automatically adapts to look great and work perfectly on all devices including mobiles, tablets, and desktops. With over 60% of UK web traffic now on mobile, this is non-negotiable for us. All our sites are also tested across major browsers before launch."
 },
 {
  "id": "kb-53",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Can you redesign my existing website?",
  "text": "category: Web Design\nq: Can you redesign my existing website?\na: Yes, website redesigns are one of our most popular services. Whether you have an outdated look, poor mobile experience, slow loading speeds, or simply want a fresh new brand direction, we can redesign your site while preserving your existing SEO rankings and content where possible."
 },
 {
  "id": "kb-54",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "What do I need to provide to get my website built?",
  "text": "category: Web Design\nq: What do I need to provide to get my website built?\na: To get started, we typically need: your logo and brand assets, your written content (text for each page), any images or photos you want to use, and details about your services/products. We can help with copywriting, photography sourcing, and branding if you don't have these yet — just let us know."
 },
 {
  "id": "kb-55",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Will I be able to update my website myself after launch?",
  "text": "category: Web Design\nq: Will I be able to update my website myself after launch?\na: Yes. We build all our websites on platforms that give you full control — WordPress sites come with a simple dashboard and we provide basic training. If you'd rather leave the updates to us, we offer affordable monthly website management plans that cover content updates, plugin maintenance, security monitoring, and backups."
 },
 {
  "id": "kb-56",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "How long does SEO take to show results in Leeds?",
  "text": "category: SEO & Marketing\nq: How long does SEO take to show results in Leeds?\na: SEO is a long-term strategy. Most businesses in Leeds begin to see measurable improvements in Google rankings and organic traffic within 3–6 months of consistent SEO work. Competitive industries may take 6–12 months. We provide monthly reports so you can track progress clearly. Unlike paid ads, SEO builds lasting, compounding results over time."
 },
 {
  "id": "kb-57",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Can you get my business to number 1 on Google in Leeds?",
  "text": "category: SEO & Marketing\nq: Can you get my business to number 1 on Google in Leeds?\na: We can't ethically guarantee a #1 ranking — anyone who promises this is not being honest with you. What we can guarantee is a data-driven, proven SEO strategy that has helped multiple Leeds businesses achieve page 1 rankings for their target keywords. Our 5.0 Google rating and 44+ client results speak for themselves."
 },
 {
  "id": "kb-58",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "What is local SEO and does my Leeds business need it?",
  "text": "category: SEO & Marketing\nq: What is local SEO and does my Leeds business need it?\na: Local SEO optimises your website and Google Business Profile to appear in searches like 'web designer Leeds' or 'plumber near me'. If you serve customers in a specific geographic area, local SEO is essential. It helps you appear in the Google Map Pack (the 3 map results at the top of local searches) — the highest-converting placement in local search."
 },
 {
  "id": "kb-59",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you run Google Ads and PPC campaigns?",
  "text": "category: SEO & Marketing\nq: Do you run Google Ads and PPC campaigns?\na: Yes. We create and manage Google Ads (PPC) campaigns for businesses across Leeds and the UK. Our PPC management includes keyword research, ad copywriting, landing page optimisation, bid management, and monthly reporting. We focus on maximising your return on ad spend (ROAS) rather than just impressions or clicks."
 },
 {
  "id": "kb-60",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you manage social media for businesses in Leeds?",
  "text": "category: SEO & Marketing\nq: Do you manage social media for businesses in Leeds?\na: Yes — we offer full social media management including content creation, scheduling, community management, and paid social campaigns across Instagram, Facebook, TikTok, and LinkedIn. We tailor our strategies to your audience and business goals, and provide monthly performance reports."
 },
 {
  "id": "kb-61",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "What's the difference between SEO and PPC?",
  "text": "category: SEO & Marketing\nq: What's the difference between SEO and PPC?\na: SEO (Search Engine Optimisation) improves your website's organic (free) rankings on Google over time — it's a long-term investment that compounds. PPC (Pay-Per-Click) lets you appear at the top of Google instantly by paying per click — great for immediate leads. Most businesses benefit from both: PPC for quick wins and SEO for long-term, sustainable growth."
 },
 {
  "id": "kb-62",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "How much does SEO cost per month in the UK?",
  "text": "category: Pricing\nq: How much does SEO cost per month in the UK?\na: Our SEO packages start from £299/month for local SEO targeting Leeds and surrounding areas. Comprehensive national SEO campaigns typically range from £500–£1,500/month depending on competitiveness and scope. All our SEO plans include a monthly report and a dedicated account manager. View our full pricing on the Pricing page."
 },
 {
  "id": "kb-63",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you require a deposit before starting work?",
  "text": "category: Pricing\nq: Do you require a deposit before starting work?\na: Yes, we require a 50% non-refundable deposit before work begins. This secures your project slot and covers our initial research, planning, and design work. The remaining 50% is due upon project completion, before the website goes live or final files are delivered."
 },
 {
  "id": "kb-64",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Are your prices inclusive of VAT?",
  "text": "category: Pricing\nq: Are your prices inclusive of VAT?\na: All prices quoted are exclusive of VAT unless stated otherwise. VAT will be added at the prevailing UK rate where applicable. We clearly itemise VAT on all invoices."
 },
 {
  "id": "kb-65",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you offer payment plans?",
  "text": "category: Pricing\nq: Do you offer payment plans?\na: For larger projects, we can discuss a staged payment plan — for example, splitting the project into milestone-based payments. This is assessed on a case-by-case basis. Please mention this when enquiring and we'll do our best to accommodate your budget."
 },
 {
  "id": "kb-66",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "What's included in your website management plans?",
  "text": "category: Pricing\nq: What's included in your website management plans?\na: Our website management plans include: regular content updates, WordPress/plugin updates, security monitoring and malware scanning, daily backups, uptime monitoring, monthly performance reports, and priority support. Plans start from £49/month. This saves you the hassle of keeping your site secure and up-to-date."
 },
 {
  "id": "kb-67",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "What is your web design process from start to finish?",
  "text": "category: Process\nq: What is your web design process from start to finish?\na: Our process has 6 stages: (1) Discovery call — we learn about your business and goals. (2) Proposal — we send a detailed quote and timeline. (3) Design — we create your design concepts for approval. (4) Development — we build the approved design. (5) Review — you test the site and we make revisions. (6) Launch — we go live and hand over everything you need."
 },
 {
  "id": "kb-68",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you work with clients across the UK or just in Leeds?",
  "text": "category: Process\nq: Do you work with clients across the UK or just in Leeds?\na: While we're based in Holbeck, Leeds, we work with clients across the whole of the UK — and internationally. Most of our collaboration happens remotely via video calls, email, and shared project documents. However, if you're local to Leeds and prefer to meet in person, we're always happy to arrange a face-to-face meeting."
 },
 {
  "id": "kb-69",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "How many revisions do I get on my website design?",
  "text": "category: Process\nq: How many revisions do I get on my website design?\na: We include 2 rounds of revisions on web design per page. Each revision round covers reasonable amends to the approved direction — such as layout tweaks, colour adjustments, and content changes. A complete change of concept or style direction after approval would be treated as a new brief. Additional revision rounds can be purchased at our standard rate."
 },
 {
  "id": "kb-70",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Can I see examples of your work before hiring you?",
  "text": "category: Process\nq: Can I see examples of your work before hiring you?\na: Yes — visit our Portfolio page to see a selection of recent projects, including websites, logos, and branding work. We also have 44+ verified Google Reviews from happy clients across Leeds and the UK. We're proud of our 5.0 Google rating and are happy to provide references on request."
 },
 {
  "id": "kb-71",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "What happens after my website launches?",
  "text": "category: Support\nq: What happens after my website launches?\na: After launch we provide a 30-day post-launch support period for any bugs or issues related to our build. We'll also walk you through how to use your website and provide any training needed. After 30 days, ongoing support is available through our website management plans."
 },
 {
  "id": "kb-72",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you provide website hosting?",
  "text": "category: Support\nq: Do you provide website hosting?\na: We don't host websites directly, but we can recommend and set up reliable UK-based hosting with providers like Kinsta, WP Engine, or SiteGround. We'll handle all the technical setup so you don't need to worry about it. Hosting costs are separate to our design fees and typically range from £10–£50/month depending on your needs."
 },
 {
  "id": "kb-73",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "What if my website has a problem after launch?",
  "text": "category: Support\nq: What if my website has a problem after launch?\na: If you're on one of our website management plans, we'll fix any issues as part of your plan. If you're not on a plan, we offer one-off support at our standard hourly rate. For any urgent issues within 30 days of launch that are directly related to our build, we'll address these free of charge."
 },
 {
  "id": "kb-74",
  "source": "faq/faqs",
  "category": "faq",
  "url": "/faq",
  "title": "Do you provide website training after handover?",
  "text": "category: Support\nq: Do you provide website training after handover?\na: Yes — we provide a training walkthrough (via video call or in person for Leeds-based clients) covering how to update content, add blog posts, manage products, and handle basic maintenance tasks. We also record the session so you have a reference to go back to. Written guides are available on request."
 },
 {
  "id": "kb-75",
  "source": "pricing/logoPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Starter",
  "text": "name: Starter\ntag: New Businesses\nprice: £79\nsub: one-time\nhighlights: \n- 1 unique logo concept\n- 2 rounds of revisions\n- PNG & JPG web-ready files\n- Basic brand colour palette\n- 5 business day delivery"
 },
 {
  "id": "kb-76",
  "source": "pricing/logoPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Professional",
  "text": "name: Professional\ntag: Most Popular\nprice: £199\nsub: one-time\nbadge: ⭐ Most Popular\nhighlights: \n- 3 unique logo concepts\n- Unlimited revisions\n- Full source files (AI, EPS, SVG)\n- Brand colour palette + typography\n- Social media profile images"
 },
 {
  "id": "kb-77",
  "source": "pricing/logoPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Brand Identity",
  "text": "name: Brand Identity\ntag: Complete Package\nprice: £399\nsub: one-time\nhighlights: \n- 5 unique logo concepts\n- Brand guidelines document\n- Business card design\n- Social media kit (6 templates)\n- Express 2-day delivery"
 },
 {
  "id": "kb-78",
  "source": "pricing/ppcPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Starter",
  "text": "name: Starter\ntag: Small Businesses\nprice: £299\nsub: /month\nadBudget: £300–£600/mo ad spend\nhighlights: \n- Google Search Ads management\n- Up to 1 campaign / 3 ad groups\n- Keyword research (50 keywords)\n- Monthly performance report\n- Conversion tracking setup"
 },
 {
  "id": "kb-79",
  "source": "pricing/ppcPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Growth",
  "text": "name: Growth\ntag: Most Popular\nprice: £499\nsub: /month\nbadge: ⭐ Most Popular\nadBudget: £600–£1,500/mo ad spend\nhighlights: \n- Google + Meta Ads management\n- Up to 3 campaigns / 9 ad groups\n- Remarketing campaigns\n- Dedicated account manager\n- Bi-weekly performance reports"
 },
 {
  "id": "kb-80",
  "source": "pricing/ppcPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Scale",
  "text": "name: Scale\ntag: Maximum Growth\nprice: £899\nsub: /month\nadBudget: £1,500+/mo ad spend\nhighlights: \n- Unlimited campaigns & ad groups\n- Google + Meta Ads + Remarketing\n- Custom landing page design\n- Weekly performance reports\n- Bi-weekly strategy calls"
 },
 {
  "id": "kb-81",
  "source": "pricing/smmPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Starter",
  "text": "name: Starter\ntag: New to Social\nprice: £299\nsub: /month\nplatforms: Up to 2 platforms\nhighlights: \n- 3 posts per week per platform\n- Monthly content calendar\n- Basic community management\n- Hashtag research & strategy\n- Monthly performance report"
 },
 {
  "id": "kb-82",
  "source": "pricing/smmPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Growth",
  "text": "name: Growth\ntag: Most Popular\nprice: £549\nsub: /month\nbadge: ⭐ Most Popular\nplatforms: Up to 3 platforms\nhighlights: \n- Daily posts (7/week) per platform\n- Story & Reel creation (up to 6/mo)\n- Full community management\n- Paid social ad campaigns\n- Dedicated social strategist"
 },
 {
  "id": "kb-83",
  "source": "pricing/smmPackages",
  "category": "pricing",
  "url": "/pricing",
  "title": "Authority",
  "text": "name: Authority\ntag: Brand Domination\nprice: £999\nsub: /month\nplatforms: Up to 5 platforms\nhighlights: \n- Daily posts + unlimited Stories/Reels\n- Influencer outreach & collaboration\n- Paid social campaigns included\n- Bi-weekly strategy calls\n- Weekly performance reports"
 },
 {
  "id": "kb-84",
  "source": "pricing/services",
  "category": "pricing",
  "url": "/pricing",
  "title": "Logo Design",
  "text": "label: Logo Design\nfrom: From £79\ndetailPath: /logo-pricing"
 },
 {
  "id": "kb-85",
  "source": "pricing/services",
  "category": "pricing",
  "url": "/pricing",
  "title": "PPC Advertising",
  "text": "label: PPC Advertising\nfrom: From £299/mo\ndetailPath: /ppc-pricing"
 },
 {
  "id": "kb-86",
  "source": "pricing/services",
  "category": "pricing",
  "url": "/pricing",
  "title": "Social Media",
  "text": "label: Social Media\nfrom: From £299/mo\ndetailPath: /smm-pricing"
 },
 {
  "id": "kb-87",
  "source": "pricing/whoIsItFor",
  "category": "pricing",
  "url": "/pricing",
  "title": "I need a logo or brand identity",
  "text": "title: I need a logo or brand identity\ndesc: Starting a new business, rebranding, or just need a professional logo that works across all media? Our one-time logo packages cover you from £79.\ntag: Logo Design\npath: /logo-pricing"
 },
 {
  "id": "kb-88",
  "source": "pricing/whoIsItFor",
  "category": "pricing",
  "url": "/pricing",
  "title": "I want instant Google visibility & more leads",
  "text": "title: I want instant Google visibility & more leads\ndesc: Already have a website but not getting enough enquiries? PPC puts you in front of people actively searching for what you offer — from day one.\ntag: PPC Advertising\npath: /ppc-pricing"
 },
 {
  "id": "kb-89",
  "source": "pricing/whoIsItFor",
  "category": "pricing",
  "url": "/pricing",
  "title": "I want to grow my social media presence",
  "text": "title: I want to grow my social media presence\ndesc: Struggling to stay consistent on social? We handle the content, posting, and community management so your brand shows up every single day.\ntag: Social Media\npath: /smm-pricing"
 },
 {
  "id": "kb-90",
  "source": "pricing/faqs",
  "category": "pricing",
  "url": "/pricing",
  "title": "Can I combine multiple services at a discounted rate?",
  "text": "q: Can I combine multiple services at a discounted rate?\na: Yes! Clients who take on two or more services get priority scheduling and we'll put together a custom bundle quote. Message us on WhatsApp and we'll work something out that fits your budget."
 },
 {
  "id": "kb-91",
  "source": "pricing/faqs",
  "category": "pricing",
  "url": "/pricing",
  "title": "Are there any setup fees on top of the monthly prices?",
  "text": "q: Are there any setup fees on top of the monthly prices?\na: No setup fees, ever. The monthly management fee covers everything — setup, strategy, execution, and reporting. For logo design packages, the price shown is the single one-time payment with nothing extra."
 },
 {
  "id": "kb-92",
  "source": "pricing/faqs",
  "category": "pricing",
  "url": "/pricing",
  "title": "Do you offer payment plans for logo design?",
  "text": "q: Do you offer payment plans for logo design?\na: Yes. For our Professional and Brand Identity packages, we offer a 50% deposit upfront and 50% on final delivery. Just mention this when you get in touch."
 },
 {
  "id": "kb-93",
  "source": "pricing/faqs",
  "category": "pricing",
  "url": "/pricing",
  "title": "How do I get started?",
  "text": "q: How do I get started?\na: The quickest way is to message us on WhatsApp. We typically respond within a few hours, and we can have a brief discovery call or just get straight into the details via chat — whatever works for you."
 },
 {
  "id": "kb-94",
  "source": "pricing/faqs",
  "category": "pricing",
  "url": "/pricing",
  "title": "What areas do you serve?",
  "text": "q: What areas do you serve?\na: We're based in Leeds but work with clients across the UK and internationally. All our services are delivered remotely, so location is no barrier."
 },
 {
  "id": "kb-95",
  "source": "logo-pricing/packages",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "Starter",
  "text": "name: Starter\ntag: Perfect for New Businesses\nprice: £79\ndescription: Everything a brand-new business or sole trader needs to get a professional identity up and running — without breaking the bank.\nfeatures: \n- 1 unique logo concept\n- 2 rounds of revisions\n- PNG & JPG files (web-ready)\n- Basic brand colour palette\n- 5 business day delivery\n- Social media profile images (NOT included)\n- Full source files (AI, EPS, SVG) (NOT included)\n- Brand guidelines document (NOT included)\n- Business card design (NOT included)\n- Social media kit (NOT included)\ncta: Get Started — £79"
 },
 {
  "id": "kb-96",
  "source": "logo-pricing/packages",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "Professional",
  "text": "name: Professional\ntag: Most Popular\nprice: £199\ndescription: For growing businesses that need a polished, versatile brand identity with full file formats and more creative options.\nfeatures: \n- 3 unique logo concepts\n- Unlimited revisions\n- PNG & JPG files (web-ready)\n- Brand colour palette + typography\n- 3 business day delivery\n- Social media profile images\n- Full source files (AI, EPS, SVG)\n- Brand guidelines document (NOT included)\n- Business card design (NOT included)\n- Social media kit (NOT included)\ncta: Get Started — £199\nbadge: ⭐ Most Popular"
 },
 {
  "id": "kb-97",
  "source": "logo-pricing/packages",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "Brand Identity",
  "text": "name: Brand Identity\ntag: Complete Package\nprice: £399\ndescription: A full end-to-end brand identity package for businesses serious about making a lasting impression across every touchpoint.\nfeatures: \n- 5 unique logo concepts\n- Unlimited revisions\n- PNG & JPG files (web-ready)\n- Brand colour palette + typography\n- Express 2 business day delivery\n- Social media profile images\n- Full source files (AI, EPS, SVG)\n- Brand guidelines document\n- Business card design\n- Social media kit (6 templates)\ncta: Get Started — £399"
 },
 {
  "id": "kb-98",
  "source": "logo-pricing/faqs",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "What file formats will I receive?",
  "text": "q: What file formats will I receive?\na: The Starter pack includes web-ready PNG & JPG files. The Professional and Brand Identity packages include full vector source files (AI, EPS, SVG) so your logo can be scaled to any size without quality loss — perfect for print and large-format uses."
 },
 {
  "id": "kb-99",
  "source": "logo-pricing/faqs",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "How many revision rounds are included?",
  "text": "q: How many revision rounds are included?\na: The Starter package includes 2 rounds of revisions. Professional and Brand Identity packages both include unlimited revisions until you are 100% happy."
 },
 {
  "id": "kb-100",
  "source": "logo-pricing/faqs",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "How long does it take?",
  "text": "q: How long does it take?\na: The Starter pack is delivered within 5 business days. Professional within 3 business days. Brand Identity within 2 business days (express). Timelines begin once we receive your brief and payment."
 },
 {
  "id": "kb-101",
  "source": "logo-pricing/faqs",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "Can I upgrade my package later?",
  "text": "q: Can I upgrade my package later?\na: Absolutely! If you start with the Starter package and want to upgrade, we'll simply charge the difference. We want to grow with your business."
 },
 {
  "id": "kb-102",
  "source": "logo-pricing/faqs",
  "category": "pricing",
  "url": "/logo-pricing",
  "title": "Do I own the logo once it's completed?",
  "text": "q: Do I own the logo once it's completed?\na: Yes — once final payment is made, you own full commercial rights to your logo. It's yours entirely."
 },
 {
  "id": "kb-103",
  "source": "smm-pricing/packages",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Starter",
  "text": "name: Starter\ntag: Great for New Businesses\nprice: £299\nperiod: /month\nplatforms: Up to 2 platforms\npostsPerWeek: 3 posts/week\ndescription: Perfect for small businesses taking their first steps on social media — professionally managed, consistent, and on-brand without the agency price tag.\nfeatures: \n- Up to 2 platforms managed\n- 3 posts per week per platform\n- Monthly content calendar\n- Brand voice & tone setup\n- Basic community management\n- Monthly performance report\n- Hashtag research & strategy\n- Story & Reel creation (NOT included)\n- Paid social ad campaigns (NOT included)\n- Dedicated social strategist (NOT included)\n- Bi-weekly strategy calls (NOT included)\n- Influencer outreach (NOT included)\ncta: Get Started — £299/mo"
 },
 {
  "id": "kb-104",
  "source": "smm-pricing/packages",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Growth",
  "text": "name: Growth\ntag: Most Popular\nprice: £549\nperiod: /month\nplatforms: Up to 3 platforms\npostsPerWeek: Daily posts\ndescription: For growing businesses ready to dominate social feeds with daily content, Stories, Reels, and paid campaigns — everything to build a loyal audience fast.\nfeatures: \n- Up to 3 platforms managed\n- Daily posts (7/week) per platform\n- Monthly content calendar\n- Brand voice & tone setup\n- Full community management & replies\n- Bi-weekly performance reports\n- Hashtag research & strategy\n- Story & Reel creation (up to 6/mo)\n- Paid social ad campaigns\n- Dedicated social strategist\n- Bi-weekly strategy calls (NOT included)\n- Influencer outreach (NOT included)\ncta: Get Started — £549/mo\nbadge: ⭐ Most Popular"
 },
 {
  "id": "kb-105",
  "source": "smm-pricing/packages",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Authority",
  "text": "name: Authority\ntag: Full Brand Domination\nprice: £999\nperiod: /month\nplatforms: Up to 5 platforms\npostsPerWeek: Daily + Stories\ndescription: The complete social media engine — all platforms, daily content, paid campaigns, influencer outreach, and a dedicated strategist growing your brand every day.\nfeatures: \n- Up to 5 platforms managed\n- Daily posts (7/week) per platform\n- Monthly content calendar\n- Brand voice & tone setup\n- Full community management & replies\n- Weekly performance reports\n- Hashtag research & strategy\n- Story & Reel creation (unlimited)\n- Paid social ad campaigns\n- Dedicated social strategist\n- Bi-weekly strategy calls\n- Influencer outreach & collaboration\ncta: Get Started — £999/mo"
 },
 {
  "id": "kb-106",
  "source": "smm-pricing/contentTypes",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Graphics & Carousels",
  "text": "title: Graphics & Carousels\ndesc: Eye-catching branded images and multi-slide carousels that stop the scroll and tell your story."
 },
 {
  "id": "kb-107",
  "source": "smm-pricing/contentTypes",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Short-Form Video & Reels",
  "text": "title: Short-Form Video & Reels\ndesc: Trending Reels and TikToks crafted to reach new audiences and drive massive organic reach."
 },
 {
  "id": "kb-108",
  "source": "smm-pricing/contentTypes",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Stories & Polls",
  "text": "title: Stories & Polls\ndesc: Daily Stories to keep your audience engaged with polls, Q&As, countdowns and behind-the-scenes."
 },
 {
  "id": "kb-109",
  "source": "smm-pricing/contentTypes",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Captions & Copywriting",
  "text": "title: Captions & Copywriting\ndesc: Punchy, brand-aligned captions with strategic calls to action and platform-optimised formatting."
 },
 {
  "id": "kb-110",
  "source": "smm-pricing/contentTypes",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Promotional Content",
  "text": "title: Promotional Content\ndesc: Seasonal campaigns, product launches, sales and offers — all designed to drive real business results."
 },
 {
  "id": "kb-111",
  "source": "smm-pricing/contentTypes",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Community Engagement",
  "text": "title: Community Engagement\ndesc: Replying to comments, DMs and mentions to build genuine relationships with your audience."
 },
 {
  "id": "kb-112",
  "source": "smm-pricing/howItWorks",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Brand Discovery",
  "text": "step: 01\ntitle: Brand Discovery\ndesc: We deep-dive into your brand, target audience, tone of voice, and competitors before creating a single piece of content."
 },
 {
  "id": "kb-113",
  "source": "smm-pricing/howItWorks",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Content Strategy",
  "text": "step: 02\ntitle: Content Strategy\ndesc: We build a monthly content calendar tailored to your goals — planned, approved, and scheduled in advance."
 },
 {
  "id": "kb-114",
  "source": "smm-pricing/howItWorks",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Create & Schedule",
  "text": "step: 03\ntitle: Create & Schedule\ndesc: Our designers and copywriters create everything. You review and approve, then we publish at the optimal times."
 },
 {
  "id": "kb-115",
  "source": "smm-pricing/howItWorks",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Report & Refine",
  "text": "step: 04\ntitle: Report & Refine\ndesc: You receive clear performance reports. We analyse what&apos;s working and constantly refine to grow your audience."
 },
 {
  "id": "kb-116",
  "source": "smm-pricing/stats",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Average follower growth in first 3 months",
  "text": "value: 2.4×\nlabel: Average follower growth in first 3 months"
 },
 {
  "id": "kb-117",
  "source": "smm-pricing/stats",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Average increase in post engagement after month 1",
  "text": "value: 68%\nlabel: Average increase in post engagement after month 1"
 },
 {
  "id": "kb-118",
  "source": "smm-pricing/stats",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Content created and approved before it goes live",
  "text": "value: 100%\nlabel: Content created and approved before it goes live"
 },
 {
  "id": "kb-119",
  "source": "smm-pricing/stats",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Response time for community management & DMs",
  "text": "value: 24hr\nlabel: Response time for community management & DMs"
 },
 {
  "id": "kb-120",
  "source": "smm-pricing/faqs",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Do I get to approve content before it's posted?",
  "text": "q: Do I get to approve content before it's posted?\na: Absolutely. Every month we send you the full content calendar for approval before anything goes live. You can request changes and we'll revise until you're happy. Nothing gets posted without your sign-off."
 },
 {
  "id": "kb-121",
  "source": "smm-pricing/faqs",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "What platforms do you manage?",
  "text": "q: What platforms do you manage?\na: We manage Facebook, Instagram, TikTok, LinkedIn, and X (Twitter). Your package determines how many platforms are included. You choose which ones matter most for your business."
 },
 {
  "id": "kb-122",
  "source": "smm-pricing/faqs",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Do I need to provide photos or videos?",
  "text": "q: Do I need to provide photos or videos?\na: Not necessarily — our team can create graphics, designed posts, and short animations using your brand assets. However, if you can provide real photos or footage of your business, products, or team, it significantly boosts authenticity and engagement."
 },
 {
  "id": "kb-123",
  "source": "smm-pricing/faqs",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Is the ad spend for paid campaigns included?",
  "text": "q: Is the ad spend for paid campaigns included?\na: No — the management fee covers our time to build and manage the ad campaigns. The actual ad spend (money paid to Facebook/Instagram/TikTok) is a separate budget paid directly by you. We recommend a minimum of £150-300/mo for meaningful results."
 },
 {
  "id": "kb-124",
  "source": "smm-pricing/faqs",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "How long before I see results?",
  "text": "q: How long before I see results?\na: Organic growth takes time — most clients see noticeable engagement improvements within 4-6 weeks and strong follower growth within 3 months. Paid campaigns can drive immediate traffic and profile visits from day one."
 },
 {
  "id": "kb-125",
  "source": "smm-pricing/faqs",
  "category": "pricing",
  "url": "/smm-pricing",
  "title": "Can I cancel at any time?",
  "text": "q: Can I cancel at any time?\na: Yes. We work on rolling monthly agreements with 30 days notice. We believe in earning your business each month through results — no long-term lock-ins."
 },
 {
  "id": "kb-126",
  "source": "ppc-pricing/packages",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Starter",
  "text": "name: Starter\ntag: Perfect for Small Businesses\nprice: £299\nperiod: /month\nadBudget: £300 – £600\ndescription: Ideal for local businesses and sole traders wanting to get in front of Google searchers fast, without a huge monthly commitment.\nfeatures: \n- Google Search Ads setup & management\n- Up to 1 campaign / 3 ad groups\n- Keyword research (up to 50 keywords)\n- Ad copywriting (2 variations per group)\n- Monthly performance report\n- Conversion tracking setup\n- Landing page recommendations\n- Meta Ads (Facebook & Instagram) (NOT included)\n- Remarketing / retargeting campaigns (NOT included)\n- Dedicated account manager (NOT included)\n- Bi-weekly strategy calls (NOT included)\ncta: Get Started — £299/mo"
 },
 {
  "id": "kb-127",
  "source": "ppc-pricing/packages",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Growth",
  "text": "name: Growth\ntag: Most Popular\nprice: £499\nperiod: /month\nadBudget: £600 – £1,500\ndescription: For growing businesses ready to scale leads across both Google and Meta — with remarketing to capture warm audiences.\nfeatures: \n- Google Search Ads setup & management\n- Up to 3 campaigns / 9 ad groups\n- Keyword research (up to 150 keywords)\n- Ad copywriting (4 variations per group)\n- Monthly performance report\n- Conversion tracking setup\n- Landing page recommendations\n- Meta Ads (Facebook & Instagram)\n- Remarketing / retargeting campaigns\n- Dedicated account manager\n- Bi-weekly strategy calls (NOT included)\ncta: Get Started — £499/mo\nbadge: ⭐ Most Popular"
 },
 {
  "id": "kb-128",
  "source": "ppc-pricing/packages",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Scale",
  "text": "name: Scale\ntag: Maximum Growth\nprice: £899\nperiod: /month\nadBudget: £1,500+\ndescription: A fully managed, multi-platform advertising engine for established businesses serious about dominating their market.\nfeatures: \n- Google Search Ads setup & management\n- Unlimited campaigns & ad groups\n- Keyword research (unlimited)\n- Ad copywriting (unlimited variations)\n- Weekly performance reports\n- Advanced conversion tracking\n- Custom landing page design\n- Meta Ads (Facebook & Instagram)\n- Remarketing / retargeting campaigns\n- Dedicated account manager\n- Bi-weekly strategy calls\ncta: Get Started — £899/mo"
 },
 {
  "id": "kb-129",
  "source": "ppc-pricing/howItWorks",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Discovery & Audit",
  "text": "step: 01\ntitle: Discovery & Audit\ndesc: We dig into your business, competitors, and target audience to identify the highest-value keywords and audiences."
 },
 {
  "id": "kb-130",
  "source": "ppc-pricing/howItWorks",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Campaign Build",
  "text": "step: 02\ntitle: Campaign Build\ndesc: Our team builds your campaigns from scratch — ad groups, copy, extensions, tracking and landing pages all set up correctly."
 },
 {
  "id": "kb-131",
  "source": "ppc-pricing/howItWorks",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Go Live & Monitor",
  "text": "step: 03\ntitle: Go Live & Monitor\ndesc: Campaigns go live and we monitor performance daily — adjusting bids, pausing underperformers, and scaling winners."
 },
 {
  "id": "kb-132",
  "source": "ppc-pricing/howItWorks",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Report & Optimise",
  "text": "step: 04\ntitle: Report & Optimise\ndesc: You receive clear monthly reports with plain-English insights. We continuously refine to lower cost-per-click and increase ROI."
 },
 {
  "id": "kb-133",
  "source": "ppc-pricing/stats",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Average ROI on Google Ads for our clients",
  "text": "value: 3.8×\nlabel: Average ROI on Google Ads for our clients"
 },
 {
  "id": "kb-134",
  "source": "ppc-pricing/stats",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Average reduction in cost-per-click after month 2",
  "text": "value: 47%\nlabel: Average reduction in cost-per-click after month 2"
 },
 {
  "id": "kb-135",
  "source": "ppc-pricing/stats",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Average time from brief to campaigns going live",
  "text": "value: 72hrs\nlabel: Average time from brief to campaigns going live"
 },
 {
  "id": "kb-136",
  "source": "ppc-pricing/stats",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Transparent — you own your ad accounts always",
  "text": "value: 100%\nlabel: Transparent — you own your ad accounts always"
 },
 {
  "id": "kb-137",
  "source": "ppc-pricing/faqs",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Is the ad spend included in your management fee?",
  "text": "q: Is the ad spend included in your management fee?\na: No — the management fee covers our time, strategy, and expertise. Your ad spend (the money paid directly to Google or Meta) is separate and paid directly by you. This keeps things fully transparent — you can see exactly where every penny goes."
 },
 {
  "id": "kb-138",
  "source": "ppc-pricing/faqs",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "How long before I see results?",
  "text": "q: How long before I see results?\na: Most clients see initial traffic and leads within the first 48–72 hours of going live. However, campaigns typically reach peak performance at the 4–8 week mark once we've gathered enough data to optimise bids and refine targeting."
 },
 {
  "id": "kb-139",
  "source": "ppc-pricing/faqs",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "What platforms do you run ads on?",
  "text": "q: What platforms do you run ads on?\na: Our Starter pack focuses on Google Search Ads. The Growth and Scale packages also include Meta Ads (Facebook & Instagram). We can also manage LinkedIn and TikTok Ads as add-ons upon request."
 },
 {
  "id": "kb-140",
  "source": "ppc-pricing/faqs",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Do I need a minimum contract length?",
  "text": "q: Do I need a minimum contract length?\na: We operate on rolling monthly agreements — no long-term lock-in. We'd rather earn your continued business through results. We do recommend a minimum of 3 months to properly optimise campaigns."
 },
 {
  "id": "kb-141",
  "source": "ppc-pricing/faqs",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Who owns the ad accounts?",
  "text": "q: Who owns the ad accounts?\na: You do — always. We set up campaigns inside your own Google Ads and Meta Business accounts. If you ever leave (though we hope you won't!), you keep everything."
 },
 {
  "id": "kb-142",
  "source": "ppc-pricing/faqs",
  "category": "pricing",
  "url": "/ppc-pricing",
  "title": "Can I change my package later?",
  "text": "q: Can I change my package later?\na: Absolutely. You can upgrade or downgrade at the start of any new monthly billing cycle. As your business grows, we grow with you."
 },
 {
  "id": "kb-143",
  "source": "about/values",
  "category": "company",
  "url": "/about",
  "title": "Innovation",
  "text": "title: Innovation\ndesc: We stay ahead of digital trends to deliver creative, forward-thinking solutions for every client."
 },
 {
  "id": "kb-144",
  "source": "about/values",
  "category": "company",
  "url": "/about",
  "title": "Passion",
  "text": "title: Passion\ndesc: We genuinely care about the success of your business and pour dedication into every project we take on."
 },
 {
  "id": "kb-145",
  "source": "about/values",
  "category": "company",
  "url": "/about",
  "title": "Integrity",
  "text": "title: Integrity\ndesc: Transparent pricing, honest communication, and no hidden surprises — always."
 },
 {
  "id": "kb-146",
  "source": "about/values",
  "category": "company",
  "url": "/about",
  "title": "Support",
  "text": "title: Support\ndesc: Our relationship does not end at launch. We provide ongoing care to ensure your website continues to grow."
 },
 {
  "id": "kb-147",
  "source": "about/milestones",
  "category": "company",
  "url": "/about",
  "title": "Where It All Began",
  "text": "year: 2014\ntitle: Where It All Began\ndesc: Elvis started freelancing from a small desk in Leeds, building websites for local businesses on a shoestring budget and a big dream."
 },
 {
  "id": "kb-148",
  "source": "about/milestones",
  "category": "company",
  "url": "/about",
  "title": "First Agency Clients",
  "text": "year: 2017\ntitle: First Agency Clients\ndesc: Word-of-mouth spread fast. Dleading took on its first retainer clients — a Leeds restaurant chain and a regional law firm — and never looked back."
 },
 {
  "id": "kb-149",
  "source": "about/milestones",
  "category": "company",
  "url": "/about",
  "title": "The Team Grows",
  "text": "year: 2019\ntitle: The Team Grows\ndesc: We hired our first full-time developer and designer, officially becoming a multi-discipline creative agency with a proper team behind the name."
 },
 {
  "id": "kb-150",
  "source": "about/milestones",
  "category": "company",
  "url": "/about",
  "title": "Hitting 100 Projects",
  "text": "year: 2021\ntitle: Hitting 100 Projects\ndesc: Completed our 100th client project — a milestone celebrated with the whole team. SEO and digital marketing became core service offerings."
 },
 {
  "id": "kb-151",
  "source": "about/milestones",
  "category": "company",
  "url": "/about",
  "title": "Company Registered",
  "text": "year: 2023\ntitle: Company Registered\ndesc: Dleading Creative Designs Ltd was officially incorporated, cementing our commitment to professionalism, growth, and long-term client partnerships."
 },
 {
  "id": "kb-152",
  "source": "about/milestones",
  "category": "company",
  "url": "/about",
  "title": "Going Stronger",
  "text": "year: 2025\ntitle: Going Stronger\ndesc: Now a team of 5 specialists delivering web design, SEO, social media, and branding to businesses across Leeds and the whole of the UK."
 },
 {
  "id": "kb-153",
  "source": "about/whyUs",
  "category": "company",
  "url": "/about",
  "title": "Strategy First, Design Second",
  "text": "title: Strategy First, Design Second\ndesc: Every project starts with a clear plan. We understand your goals before we open a single design tool."
 },
 {
  "id": "kb-154",
  "source": "about/whyUs",
  "category": "company",
  "url": "/about",
  "title": "We Treat Every Client Like a Partner",
  "text": "title: We Treat Every Client Like a Partner\ndesc: You will always speak to a real person who knows your project inside out — no outsourcing, no call centres."
 },
 {
  "id": "kb-155",
  "source": "about/whyUs",
  "category": "company",
  "url": "/about",
  "title": "Proud to Be Leeds-Based",
  "text": "title: Proud to Be Leeds-Based\ndesc: We understand the local market, the local customer, and what it takes to stand out in a competitive UK landscape."
 },
 {
  "id": "kb-156",
  "source": "about/whyUs",
  "category": "company",
  "url": "/about",
  "title": "Results You Can Actually Measure",
  "text": "title: Results You Can Actually Measure\ndesc: We track rankings, traffic, leads, and conversions — so you always know exactly what your investment is delivering."
 },
 {
  "id": "kb-157",
  "source": "about/whyUs",
  "category": "company",
  "url": "/about",
  "title": "On Time, Every Time",
  "text": "title: On Time, Every Time\ndesc: Deadlines are not suggestions. We deliver on schedule and keep you informed every step of the way."
 },
 {
  "id": "kb-158",
  "source": "about/whyUs",
  "category": "company",
  "url": "/about",
  "title": "Fair, Transparent Pricing",
  "text": "title: Fair, Transparent Pricing\ndesc: No confusing packages or surprise invoices. You know exactly what you are paying for and why."
 },
 {
  "id": "kb-159",
  "source": "components/steps",
  "category": "process",
  "url": "/",
  "title": "Free Strategy Call",
  "text": "number: 01\ntitle: Free Strategy Call\ndescription: We learn about your business, your customers, and your goals. No obligation — just a clear plan for getting you more customers.\ntags: \n- Free Consultation\n- Goal Setting\n- Market Research"
 },
 {
  "id": "kb-160",
  "source": "components/steps",
  "category": "process",
  "url": "/",
  "title": "We Build Your Plan",
  "text": "number: 02\ntitle: We Build Your Plan\ndescription: We create a tailored growth plan — Google Ads, SEO, or a new website — whatever gets you customers fastest.\ntags: \n- Google Ads\n- SEO Strategy\n- Website Plan"
 },
 {
  "id": "kb-161",
  "source": "components/steps",
  "category": "process",
  "url": "/",
  "title": "We Go Live",
  "text": "number: 03\ntitle: We Go Live\ndescription: Your campaigns go live or your site launches. Fast turnaround. Everything set up to generate calls and bookings from day one.\ntags: \n- Fast Launch\n- Mobile-First\n- SEO Ready"
 },
 {
  "id": "kb-162",
  "source": "components/steps",
  "category": "process",
  "url": "/",
  "title": "You Get Customers",
  "text": "number: 04\ntitle: You Get Customers\ndescription: Calls come in. Bookings increase. Sales grow. We track everything and report clearly so you always see your results.\ntags: \n- More Calls\n- More Bookings\n- Clear Reporting"
 },
 {
  "id": "kb-163",
  "source": "components/steps",
  "category": "process",
  "url": "/",
  "title": "We Scale What Works",
  "text": "number: 05\ntitle: We Scale What Works\ndescription: Once leads are flowing, we double down on what's working. More ads, better rankings, more customers every month.\ntags: \n- Scale Up\n- Optimise\n- More Revenue"
 },
 {
  "id": "kb-164",
  "source": "components/steps",
  "category": "process",
  "url": "/",
  "title": "Ongoing Support",
  "text": "number: 06\ntitle: Ongoing Support\ndescription: We don't disappear after launch. We're with you every step — maintaining, optimising, and growing your lead flow.\ntags: \n- Dedicated Support\n- Monthly Growth\n- No Lock-in"
 },
 {
  "id": "kb-165",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "Google Ads",
  "text": "title: Google Ads\ndescription: Start getting customers fast. We run targeted campaigns that put your business in front of people searching for your service right now.\nhash: digital-marketing"
 },
 {
  "id": "kb-166",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "SEO",
  "text": "title: SEO\ndescription: Grow your business long-term. We get your website ranking on Google so customers find you — without paying for every click.\nhash: seo"
 },
 {
  "id": "kb-167",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "Google Business Optimisation",
  "text": "title: Google Business Optimisation\ndescription: Get found locally and build trust. We optimise your Google Business profile so you appear in local searches and stand out from competitors.\nhash: web-design"
 },
 {
  "id": "kb-168",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "Website Optimisation",
  "text": "title: Website Optimisation\ndescription: Turn visitors into customers. We improve your existing site — speed, layout, and copy — so more people call, book, and buy.\nhash: web-design"
 },
 {
  "id": "kb-169",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "Custom Website Design",
  "text": "title: Custom Website Design\ndescription: A website built to convert — fast, mobile-ready, and designed to generate real enquiries for your business.\nhash: web-design"
 },
 {
  "id": "kb-170",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "E-commerce Website Development",
  "text": "title: E-commerce Website Development\ndescription: Online stores built to sell. Every page designed to reduce drop-off and increase orders.\nhash: ecommerce"
 },
 {
  "id": "kb-171",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "Website Management",
  "text": "title: Website Management\ndescription: We handle updates, security, and performance so your site stays fast and never loses a customer.\nhash: management"
 },
 {
  "id": "kb-172",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "Logo & Brand Design",
  "text": "title: Logo & Brand Design\ndescription: A strong brand builds instant trust. Stand out from every competitor in your area.\nhash: logo"
 },
 {
  "id": "kb-173",
  "source": "components/services",
  "category": "services",
  "url": "/",
  "title": "Video Animation",
  "text": "title: Video Animation\ndescription: Explain what you do in 60 seconds and turn more website visitors into paying customers.\nhash: video"
 },
 {
  "id": "kb-174",
  "source": "knowledge/company.md",
  "category": "company",
  "url": null,
  "title": "Company name and location",
  "text": "Company: Dleading Creative Designs Ltd (also written \"Dleading Creative Design Ltd\").\nWebsite: creativedleading.co.uk\nOffice location: Holbeck, Leeds, West Yorkshire, United Kingdom.\nFocus: helping local service businesses in Leeds get more clients online through websites, SEO and Google Ads."
 },
 {
  "id": "kb-175",
  "source": "knowledge/company.md",
  "category": "company",
  "url": null,
  "title": "Contact details",
  "text": "Phone / WhatsApp: +44 742 725 9935\nWhatsApp link: https://wa.link/9m4r50\nEmail: info@creativedleading.co.uk\nContact page: https://creativedleading.co.uk/contact\nThese are the ONLY official contact details."
 },
 {
  "id": "kb-176",
  "source": "knowledge/company.md",
  "category": "company",
  "url": null,
  "title": "Working hours",
  "text": "Monday to Friday: 9:00am – 6:00pm\nSaturday: 10:00am – 3:00pm\nSunday: not listed on the website."
 },
 {
  "id": "kb-177",
  "source": "knowledge/company.md",
  "category": "company",
  "url": null,
  "title": "Services offered (as listed on the contact form)",
  "text": "- Custom Website Design\n- Web & Mobile Development\n- E-commerce Development\n- Search Engine Optimization (SEO)\n- Website Management\n- Graphic Design Services\nAlso has dedicated pricing pages for: logo design, social media management (SMM) and PPC / Google Ads management."
 },
 {
  "id": "kb-178",
  "source": "knowledge/company.md",
  "category": "company",
  "url": null,
  "title": "How to get a quote",
  "text": "Customers can request a free, no-obligation quote by: using the contact form on the Contact page, messaging on WhatsApp, emailing info@creativedleading.co.uk, or leaving their details with this chat assistant so the team can get back to them."
 }
];
